### ISSUE TITLE
DOT and global/graph attributes? 

### ISSUE THREAD

**Issue by cv711** [TLmaK0/gravizo#11]
Hi,

I'm trying to set the font for the graph like this:

```
digraph G {
    -Gfontname="Trebuchet MS"
    ...
}
```

but nothing seems to be happening. The "converter" doesn't respect it either and it doesn't throw any errors. Initially, I though I was doing something wrong with the `fontname` value, but If I add it individually to each element it respects it.

Also since we are on that subject the `-N` and `-E` operators for global attributes for all the nodes and edges don't seem to have any effect either.

Thanks, 
Chris

**Comment by TLmaK0** [comment]
Hi @cv711, can you point me to this feature at dot documentation?

**Comment by cv711** [comment]
Ha!

I was using this [paper](https://www.ocf.berkeley.edu/~eek/index.html/tiny_examples/thinktank/src/gv1.7c/doc/dotguide.pdf) as my reference and I was trying to set some of the graph attributes described in the table in page 6. e.g. `fontname` but when I was looking at the syntax I jumped into the Command Line Options without realising it. Sorry about that!

However, the issue on how to set the `fontname` on a graph level remains. 
Following, this [doc](http://www.graphviz.org/doc/info/attrs.html) this time it also defines that `fontname` is a graph attribute. 
So something like this:

```
digraph G {
    fontname="Trebuchet MS"
    ...
}
``` 

should probably work right? 
It doesn't complain, but it doesn't seem to respect it either.

Thanks.

**Comment by TLmaK0** [comment]
I think this property is only available for SVG output. There is a feature request #2 to allow it.

**Comment by cv711** [comment]
I see... Thanks for your time.
