### ISSUE TITLE
Newly Rendered Images bugging out

### ISSUE THREAD

**Issue by TotesCrayCray** [TLmaK0/gravizo#12]
I'm noticing that anything newly generated with gravizo has suddenly started rendering oddly. Boxes are rendering with a crooked border and extra lines are often being added. This is even occurring with  simple diagrams... 

For instance, a simple Plant UML diagram:
```
![](http://g.gravizo.com/g?
@startuml;
class MyClass{;
};
@enduml;
)
```

Turn into this: 
![image](https://cloud.githubusercontent.com/assets/5193239/13959782/7dd901f2-f023-11e5-918f-921ce572c009.png)

If I add any sort of arrows, things get a bit worse.
```
![](http://g.gravizo.com/g?
@startuml;
interface MyInterface{;
};
class Factory{;
};
Factory-+MyInterface;
@enduml;
)
```
![image](https://cloud.githubusercontent.com/assets/5193239/13959930/19ea12a2-f024-11e5-8e90-acbc8d1221ff.png)

**Comment by TLmaK0** [comment]
Thanks, @TotesCrayCray it should work ok now. There is a problem when the process works for a long time. I'm working with plantuml to try to arrange this, but I need to add SVG export before.

**Comment by TLmaK0** [comment]
Related to #8
