### ISSUE TITLE
Cardinality Handle

### ISSUE THREAD

**Issue by lionel-deglise** [TLmaK0/gravizo#19]
Hi,

Gravizo is a very useful tool. Thanks.

Cardinalty on relations seems not working. Image generation fails on test URL or undirect.

However the same puml works great on plantuml.

[dataexchange.puml.txt](https://github.com/TLmaK0/gravizo/files/630929/dataexchange.puml.txt)
![image](https://cloud.githubusercontent.com/assets/19615637/20883840/6c6171e4-bae8-11e6-8c50-3da6ac8486cd.png)

**Comment by TLmaK0** [comment]
thamks @lionel-deglise, I will take a look

**Comment by TLmaK0** [comment]
Fixed
