### ISSUE TITLE
Export as SVG

### ISSUE THREAD

**Issue by marionebl** [TLmaK0/gravizo#2]
Hey there, 

any chance Gravizo could add support for different image formats? I think about something in line with:
```
![Alt text](http://g.gravizo.com/g?
@startuml;
component "Gravizo" as gravizo;
component "Callsite" as callsite;
callsite -> gravizo : specifies format;
gravizo -> callsite : delivers format;
@enduml;
.(svg|jpeg|png) # New magic happens here
```

**Comment by TLmaK0** [comment]
Thanks Marionebl, I will added this to the roadmap.

**Comment by marionebl** [comment]
:+1:  Awesome!

**Comment by yaronyg** [comment]
+1! The PNGs generated by PlantUML (I'm guessing this is really GraphViz, but whatever) always seem a bit fuzzy. But SVG (for obvious reasons given how its rendered) is always super sharp and infinitely scalable. The later part is really nice for folks with eye issues as they can zoom the picture as large as they want and still get 100% fidelity.

**Comment by TLmaK0** [comment]
SVG output it's ready. Only need to replace http://g.gravizo.com/g? by http://g.gravizo.com/svg? and http://g.gravizo.com/source? by http://g.gravizo.com/source/svg?

![Alt text](http://g.gravizo.com/svg?
  digraph G {
    aize ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf};
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
)
