### ISSUE TITLE
PlantUML Sequence Diagrams

### ISSUE THREAD

**Issue by konsumer** [TLmaK0/gravizo#21]
The sequence diagram you have as an example in the README doesn't render correctly:

It should look like this:

![expected](https://cloud.githubusercontent.com/assets/83857/21831672/5e5b9424-d75a-11e6-9b0b-ff659b6499e6.png)

But it looks like this:

![actual](https://cloud.githubusercontent.com/assets/83857/21831677/6bc45286-d75a-11e6-9602-fdad23e6abec.png)

(note lines connecting top-right of "First Class")

Here is the current inline version:

![Alt text](https://g.gravizo.com/g?
@startuml;
actor User;
participant "First Class" as A;
participant "Second Class" as B;
participant "Last Class" as C;
User -> A: DoWork;
activate A;
A -> B: Create Request;
activate B;
B -> C: DoWork;
activate C;
C --> B: WorkDone;
destroy C;
B --> A: Request Created;
deactivate B;
A --> User: Done;
deactivate A;
@enduml)

**Comment by TLmaK0** [comment]
Hi @konsumer, this is a duplicated of #16, every day the dot service is restarted to workaround it, so It should work today. I'm investigating it.

**Comment by konsumer** [comment]
Sorry, and thanks!
