### ISSUE TITLE
Long lines drawn in diagram

### ISSUE THREAD

**Issue by jeppefrandsen** [TLmaK0/gravizo#23]
There are some long lines drawn wrongly in the diagrams. Also visible on http://www.gravizo.com. Can you have a look?

Thanks a lot for a great service! 👍

**Comment by TLmaK0** [comment]
Thanks @jeppefrandsen, I'm currently working on it #16 , meanwhile the service is restarted every day to workarond the problem. You can use svg graphs, because they are not affected.
