### ISSUE TITLE
PlantUML borders rendering issue

### ISSUE THREAD

**Issue by tbrannam** [TLmaK0/gravizo#24]
It appears the sequence diagrams have a rendering glitch.  The screenshot below is from the Gravizo.com site.

![screen shot 2017-01-23 at 10 55 49 am](https://cloud.githubusercontent.com/assets/78813/22211414/ed9edcf4-e15a-11e6-8f96-815c6fb411bb.png)

**Comment by TLmaK0** [comment]
Thanks @tbrannam, there is already an open issue #16, I'm investigating it.
