### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by gmpl** [TLmaK0/gravizo#25]
Hola Hugo,

PlantUML supports links, but it  seems that Gravizo ignore them.

Here are some examples:
http://plantuml.sourceforge.net/qa/?qa=90/web-links-in-generated-images-e-g-using-image-maps

I'm looking for something to generate a simple class diagram but with hyperlinks that takes you directly to the doc of the entity.

Thanks

**Comment by TLmaK0** [comment]
Thanks @gmpl

**Comment by gmpl** [comment]
Actually this feature seems to be working.
You need to embed the link in an object, here's an example:

    <object data="http://g.gravizo.com/svg?
    @startuml;
    abstract class Bob {;
      [[http://www.example.com]];
    };
    Bob -> Alice : hello;
    @enduml"></object>

If you embed this in an html page you will see a diagram with an hyperlink in Bob.

**Comment by TLmaK0** [comment]
Thanks @gmpl for the info!!!
