### ISSUE TITLE
Actor is Hardcoded to User

### ISSUE THREAD

**Issue by chunkiat82** [TLmaK0/gravizo#28]
![graph](https://g.gravizo.com/svg?
@startuml;
actor SpringBoot;
participant "First Class" as A;
participant "Second Class" as B;
participant "Last Class" as C;
User -> A: DoWork;
activate A;
A --> User: Done;
deactivate A;
@enduml)

![image](https://cloud.githubusercontent.com/assets/275445/23790138/cb64f254-05b8-11e7-8326-14356158c268.png)

**Comment by TLmaK0** [comment]
Hi @chunkiat82, I'm not sure were is the problem. Can you give me what your are expecting from this graph? Some thing like this?:

![graph](https://g.gravizo.com/svg?
@startuml;
actor SpringBoot;
participant "First Class" as A;
participant "Second Class" as B;
participant "Last Class" as C;
SpringBoot -> A: DoWork;
activate A;
A --> SpringBoot: Done;
deactivate A;
@enduml
)
