### ISSUE TITLE
Support CJK ?

### ISSUE THREAD

**Issue by wenerme** [TLmaK0/gravizo#3]
e.g.

```
digraph G {
   a->b;
   a[label="你好"]
 }
```

<img src='http://g.gravizo.com/g?
digraph G {
   a->b;
   a[label="你好"]
 }
'>

**Comment by TLmaK0** [comment]
Hi @wenerme, actually doesn't support CJK, I will add this to the roadmap.

**Comment by TLmaK0** [comment]
@wenerme Gravizo now support CJK characters

![Alt text](http://g.gravizo.com/g?
digraph G {
   a->b;
   a[label="你好"]
 }
)
