### ISSUE TITLE
Busted?

### ISSUE THREAD

**Issue by cosmocracy** [TLmaK0/gravizo#30]
Looking at the README here, none of the diagrams are rendering (instead showing jumbled lines of the underlying DOT (etc.)). 

For example:
![image](https://cloud.githubusercontent.com/assets/10222432/24149515/2bc6ecfc-0e19-11e7-9e75-b562ce4d2e7c.png)

**Comment by TLmaK0** [comment]
Hi @cosmocracy after markdown changes github doesn't allow multiple lines in images. You should use indirect way #29

**Comment by cosmocracy** [comment]
Don't you want to at least update the README examples? To the outside world it looks completely broken :-/

**Comment by TLmaK0** [comment]
yes sure, this is why I still open the other issue.
