### ISSUE TITLE
Supporting { and } in UML?

### ISSUE THREAD

**Issue by FantasticFiasco** [TLmaK0/gravizo#32]
It seems that { and } isn't supported in UML when it comes to being displayed indirectly on GitHub.

I have the following UML:

```
@startuml;
actor User;
participant "Relay service" as A;
participant "Key/value service" as B;

User -> A: GET /relay/{key};
activate A;

A -> B: GET /store/{key};
activate B;

B -> A: {"key":"{key}", "value":"{value}"};
deactivate B;

A -> User:  {"key":"{key}", "value":"{value}"};
deactivate A;

@enduml
```

It doesn't not seem to be rendered correctly. For reference, see [this](https://github.com/FantasticFiasco/web-server-tech-benchmark/blob/branches/uml/README.md).

Thanks for a really cool project!

**Comment by TLmaK0** [comment]
Hi @FantasticFiasco, I try it ant seams works, can you provide more info?

**Comment by FantasticFiasco** [comment]
Sure, take a look [at this](https://github.com/FantasticFiasco/gravizo/blob/master/ERROR.md). The only thing differing is `{` and `}`.

**Comment by TLmaK0** [comment]
Fixed
