### ISSUE TITLE
allow gravizo in gitlab Rdoc format wiki

### ISSUE THREAD

**Issue by LuisBL** [TLmaK0/gravizo#35]
In gitlab README.rst and wiki(s) we set RestructuredText (Rdoc) format instead of  not Markdown.
Can we use Gravizo with Restructuredtext (gitlab/wiki/format Rdoc) ?

**Comment by TLmaK0** [comment]
I didn't test it with rdoc, but any document that it's able to show an external image should works with Gravizo. Only need to put the the image url like in Github. If rdoc doesn't allows multiline image source, you should use indirect way. Tell me if you successfully make it work, or if you want, could you provide me a way to test it?
