### ISSUE TITLE
Class Diagrams

### ISSUE THREAD

**Issue by kevinchau321** [TLmaK0/gravizo#36]
I can't get class diagrams to work using DOT syntax. I've tried using the tester/encoder to get something that gravizo can parse, but its not rendering correctly.

Here's the diagram I am trying to render and what it should look like:
```
digraph G {
        node [shape = "record"]

        Animal [
                label = "{Animal|+ name : string\l+ age : int\l|+ die() : void\l}"
        ]
}
```
![image](https://cloud.githubusercontent.com/assets/6045301/25765325/4951561c-31a1-11e7-9821-874b60379c6c.png) (generated with webgraphviz.com)

Here's what the tester/encoder is giving me:
![image](https://cloud.githubusercontent.com/assets/6045301/25765345/70227a64-31a1-11e7-8db9-8584b9567e0a.png)

It seems to separate the class in to individual boxes.

**Comment by kevinchau321** [comment]
I've also tried using UMLGraph syntax, but it won't render properly when given an asterisk (*), i.e. when declaring pointers in my class diagram.

**Comment by kevinchau321** [comment]
I have also been unsucessful in getting any plantUML to render in markdown

**Comment by TLmaK0** [comment]
Hi @kevinchau321, there are several replacements for chars in url (like + by space), try to use indirect way http://www.gravizo.com/#howto
