### ISSUE TITLE
Gravizo.com documentation out of date?

### ISSUE THREAD

**Issue by jkochaniak** [TLmaK0/gravizo#38]
I think the documentation for the indirect method on the gravizo.com [How to use](http://www.gravizo.com/#howto) page is incorrect. It says that to use Gravizo indirectly, you need to use an url like:

`https://g.gravizo.com/`**`source/svg?`**`<source_url_url_encoded>`

However, this doesn't work for me. What does work is:

`https://g.gravizo.com/`**`source?`**`<source_url_url_encoded>`

e.g. this link https://g.gravizo.com/source/svg?https%3A%2F%2Fgist.githubusercontent.com%2Fjkochaniak%2F42b2f2823617471b38120ed3012abb75%2Fraw%2F547473b04c18bce8d933584f1f65208ebd47cff8%2Ftest.txt

shows me a graph_not_found image. But this link:

https://g.gravizo.com/source?https%3A%2F%2Fgist.githubusercontent.com%2Fjkochaniak%2F42b2f2823617471b38120ed3012abb75%2Fraw%2F547473b04c18bce8d933584f1f65208ebd47cff8%2Ftest.txt

renders my diagram.

Just wanted to point this out since I lost some time figuring out how to make it work. Thank you so much for making this tool and website!

**Comment by TLmaK0** [comment]
@jkochaniak thanks, I just upload a new version that fixes this exactly problem. Thanks for reporting it!!! Now two graphs works perfectly!
