### ISSUE TITLE
github indirect way to present diagrams does not work

### ISSUE THREAD

**Issue by louisrubet** [TLmaK0/gravizo#40]
Hi TLmaK0
thank you for your nice work !

It appears that github indirect way to present diagrams does not work
It only shows boxes next to each other and without arrows nor lines

I wasn't able to manage it

look at
![Alt text](https://g.gravizo.com/source/custom_mark10?https://github.com/louisrubet/projectproof/blob/master/README.md)
<summary></summary>
custom_mark10
 digraph G {
   main -> parse -> execute;
   main -> init;
   main -> cleanup;
   execute -> make_string;
   execute -> printf
   init -> make_string;
   main -> printf;
   execute -> compare;
 }
custom_mark10
</details>

What do you think about it ?

**Comment by TLmaK0** [comment]
Hi @louisrubet, look at source code of my working version https://github.com/TLmaK0/projectproof/blob/master/README.md
I think the problem is the ; after printf and the raw file.

**Comment by louisrubet** [comment]
:)
