### ISSUE TITLE
low quality/resolution

### ISSUE THREAD

**Issue by zvictor** [TLmaK0/gravizo#44]
First of all, thank you for such nice and handy service!  💪

I started using it in my project (https://github.com/Quadric/radiaction/tree/master/examples/with-webtask#infrastructure) and even though everything works, the image rendered has very low quality.

I understand that the space is quite narrow and not optimal for such graph, but the same graph and the same viewport render with a way higher resolution at http://viz-js.com/

Would it possible to increase the resolution of the rendered images provided by gravizo?

**Comment by TLmaK0** [comment]
HI @zvictor, do you test the svg output format?  only need to add svg to url https://g.gravizo.com/source/svg/custom_mark?https%3A%2F%2Frawgit.com%2FQuadric%2Fradiaction%2Fmaster%2Fexamples%2Fwith-webtask%2FREADME.md

**Comment by zvictor** [comment]
now it's great! thanks again. 🍻
