### ISSUE TITLE
How to get encoded url?

### ISSUE THREAD

**Issue by juliangaal** [TLmaK0/gravizo#45]
I saw in the other issue that Github removed a feature which forces us to use the indirect way: 
`https://g.gravizo.com/source/svg?<source_url_url_encoded>`

How do I get this `<source_url_url_encoded>`?

EDIT: followed [this tutorial](https://gist.github.com/svenevs/ce05761128e240e27883e3372ccd4ecd), but get `@startuml digraph Syntax error? did you mean digraph"`
Thanks

**Comment by TLmaK0** [comment]
First create a public page where you want to include the graph.
Create a comment where you include the graph text between marks.
Then create a url encoded from an online site like https://meyerweb.com/eric/tools/dencoder/
Take a look to the README file in this github repo.
I hope I have helped you with this issue.
