### ISSUE TITLE
Weird behavior when using UMLGraph syntax

### ISSUE THREAD

**Issue by MashenKa737** [TLmaK0/gravizo#46]
I worked with class diagram. Used direct way of usage from http://www.gravizo.com page

When I try to write generic types, i.e. MockClazz<T> it can't generate picture. When I try to replace '<>' with <%3C%3E> it draws 'cXXX' instead of class where 'XXX' are random numbers that change when the page is reloaded.

One more.
It can't generate a picture from text with both class/interface and enum. However, it can creates pictures of enums, when there are no classes.

**Comment by TLmaK0** [comment]
Hi @MashenKa737, can you provide a full example?

**Comment by TLmaK0** [comment]
Closed by inactivity
