### ISSUE TITLE
Can I use the gravizo directly.

### ISSUE THREAD

**Issue by SeanYanxml** [TLmaK0/gravizo#48]
I read your `read.me` file. I find you use the direct url and the annonation.
When i write the class graph in `macDown`( One kind of software of mac). I think it can't use the example of the official website.
```
![Alt text](https://g.gravizo.com/svg?
  digraph G {
    aize ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf}
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
)
```
By the way, your must use the url like `![Alt text](http://g.gravizo.com/source/gravizosample?https%3A%2F%2Fbitbucket.org%2FTLmaK0%2Fgravizo-example%2Fraw%2Fmaster%2FREADME.md#`.

Any good ideas?

**Comment by TLmaK0** [comment]
Hi Sean,

I don't have right now a Mac here to test it, but could be a problem with multi-line url images. Try to remove all new lines and check if it works. If works then this is the problem.

```
![Alt text](https://g.gravizo.com/svg?  digraph G {    aize ="4,4";    main [shape=box];    main -> parse [weight=8];    parse -> execute;    main -> init [style=dotted];    main -> cleanup;    execute -> { make_string; printf}    init -> make_string;    edge [color=red];    main -> printf [style=bold,label="100 times"];    make_string [label="make a string"];    node [shape=box,style=filled,color=".7 .3 1.0"];    execute -> compare;  })
```
