### ISSUE TITLE
What is <url_source_url_encoded>? How do I get it for my project?

### ISSUE THREAD

**Issue by vitiral** [TLmaK0/gravizo#49]
This project looks cool, but I'm confused by this line:

> Use this syntax: ```![Alt text](https://g.gravizo.com/source/<custom_mark>?<url_source_url_encoded>```). And use html comment or summary tag ```<details><summary></summary></details>``` 

It looks like `<custom_mark>` is something like `custom_mark10`, but `<url_source_url_encoded>` looks like it is somehow project related?

**Comment by TLmaK0** [comment]
Gravizo, will get the source page of <url_source_url_endoded> and search for the code between the first <custom_mark> and the next <custom_mark> in the source, then will use the text inside as code. Look at the README.md examples.

**Comment by vitiral** [comment]
Gotcha! I just tried copy+pasting and it worked! Thanks!
