### ISSUE TITLE
support indirection

### ISSUE THREAD

**Issue by mathroc** [TLmaK0/gravizo#5]
sometimes the graph description is too long for GitHub (but works fine with the gravizo test/encoder), it would be nice to be able to do something like describe here : http://stackoverflow.com/a/32771815/274188

tl;dr: 

I'd like to have an url like this : http://g.gravizo.com/g?http://somewhere.org/graph-source.txt
where http://somewhere.org/graph-source.txt contains either Graph source supported by graphvizo (eg: graphviz)

I would use it like so : http://g.gravizo.com/g?https://raw.githubusercontent.com/wiki/org/project/graph1.md so that when I update the wiki page "graph1", the image generated by http://g.gravizo.com/g?https://raw.githubusercontent.com/wiki/org/project/graph1.md is updated accordingly

note: It may also remove the need to encode the Graph source and remove some [incompatibilities](http://www.gravizo.com/#incompatibilities)

but I don't how it would work with the CDN

**Comment by TLmaK0** [comment]
Thanks @mathroc, I need to think more about this, but It could be good start. As you say CDN is a problem.

**Comment by TLmaK0** [comment]
Hi @mathroc, now there is a new syntax to support this on #6

**Comment by mathroc** [comment]
awesome! thank you @TLmaK0 !
