### ISSUE TITLE
No @startuml found

### ISSUE THREAD

**Issue by jeanrajotte** [TLmaK0/gravizo#50]
Great tool, thanks.

Working with it in Github private repos is difficult. It used to work, but something has changed and URL-encoded diagram definition is broken now.

Because the repo is private, one can't use the `indirect` method - the source is not accessible.

For the direct method, Github markdown does not support multi-line `<img>` or `![]()` images.

Therefore one must url-encode the multi-line diagram. However, the processor no longer accepts the input (this used to work).  

Identical input shown here, first without "Extra compatibility", it works, but not the other way.  

![screen shot 2019-02-28 at 07 21 17](https://user-images.githubusercontent.com/312996/53566311-cb2e0700-3b29-11e9-9ad5-a5efee6480f6.jpg)
![screen shot 2019-02-28 at 07 22 46](https://user-images.githubusercontent.com/312996/53566312-cb2e0700-3b29-11e9-91a4-6256e8f9ccc5.jpg)

**Comment by jeanrajotte** [comment]
In case it's my diagram definition that's problematic, here's its source.

```
@startuml

object partner

object partner_option

partner_option : x.mode.new.02.00 = null or Y

object end_user

end_user : x_mode = null or Y

object subscription
object sku

sku : mode = null or Y

object sku_set

partner o-- partner_option
partner o-- end_user
end_user o-- subscription
sku o-- subscription
sku_set o-- partner 
sku_set o-- sku

@enduml
```

**Comment by jeanrajotte** [comment]
FYI, while playing around a little...  Removing the `@` in front of `@enduml`  yields the "No @startuml found" image also.  Possibly the "No @startuml found" error is a red herring...

**Comment by jeanrajotte** [comment]
Wow! Now it works. url-encoded returns an image. I end every line with semi-colon now.  Was that the issue?

**Comment by TLmaK0** [comment]
yes sure! When the request arrives to the server, it arrives without carriage returns, so, adding ";" is the only way to take care about this.

**Comment by jeanrajotte** [comment]
But, aren't carriage returns url-encoded?

**Comment by TLmaK0** [comment]
Yes, if you use url encode of course, but if you use a direct link no, so the system always expect a ;
