### ISSUE TITLE
icon hides content

### ISSUE THREAD

**Issue by tischi** [TLmaK0/gravizo#51]
Hello!

Great tool!

In below example the Gravizo icon partly hides the content. 

1. Do you know how to change that?

I just paste the code, because it would not render here....

2. Do you know why it does not render?

```
<img src='https://g.gravizo.com/svg?
 digraph G {
    lookup_table -> image_appearance [label="  changes"];
    image_appearance -> scientific_message [label="  changes"];
  }
'/>
```

**Comment by TLmaK0** [comment]
Hi @tischi, actually there is no way to move the gravizo icon, you can remove it if you have the Enterprise subscription.
If you are trying to render this in Github you must to use the indirect way https://github.com/TLmaK0/gravizo#new-the-indirect-way

**Comment by tischi** [comment]
Thanks!
