### ISSUE TITLE
Gravizo.com is down

### ISSUE THREAD

**Issue by jeppefrandsen** [TLmaK0/gravizo#54]
It looks as gravizo.com is down?

**Comment by TLmaK0** [comment]
Tx @jeppefrandsen, I'm just investigating the issue. The server has been removed from the ISP without notification. I will wake-up ASAP:

**Comment by TLmaK0** [comment]
@jeppefrandsen now it's up and running. We thank you for your patience during this downtime and apologize for any inconvenience caused.
