### ISSUE TITLE
How to refer to single file graph ?

### ISSUE THREAD

**Issue by hlung** [TLmaK0/gravizo#55]
I see in your readme you use `custom_mark10` and such to refer to one of many graphs in one file. What if I have a file with only one graph? How do I refer to that graph without the use of `custom_mark10`?

**Comment by TLmaK0** [comment]
Hi @hlung, now can use it without the mark `https://g.gravizo.com/source/svg?https://raw.githubusercontent.com/TLmaK0/gravizo/master/sample.txt`
