### ISSUE TITLE
Faulty rendering with big uml

### ISSUE THREAD

**Issue by marionebl** [TLmaK0/gravizo#8]
With big uml descriptions gravizo renders black strokes from the upper edge to each component, the borders of the components are missing:

![bug-report](https://cloud.githubusercontent.com/assets/4248851/12415501/4cd046f0-be9c-11e5-8d02-d22a57612da7.png)

Used definition:
```
![woo](http://g.gravizo.com/g?
@startuml;
skinparam monochrome true;
skinparam shadowing false;
skinparam component {;
  backgroundColor<<artifact:npm>> lightgray;
  componentFontColor<<artifact:fooofoo>> white;
};
component "meh" {;
  component [foo-bar] as foo.pp.git;
  component [foo-baz-fizz] as foo.bs.git;
  component [foo-looloo] as foo.looloo.git;
  component [foo-baz-protoype-sisi] as foo.sisi.git;
  component [foo-baz-frame] as foo.frame.git;
};
component "mah" {;
  component [foo-bar-ham] as foo.pp.ham.woom;
  component [foo-bar-ham-deploy] as foo.pp.ham.deploy;
  component [foo-bar-cloud-deploy] as foo.pp.cloud.deploy;
  component [foo-buzz] as foo.buzz.woom;
  component [foo-baz-fizz-ham-deploy] as foo.bs.ham.deploy;
  component [foo-baz-fizz-cloud-deploy] as foo.bs.cloud.deploy;
  component [foo-baz-fizz-ham] as foo.bs.woom;
  component "foo-baz-sums" as foo.sums;
  component [foo-looloo] as foo.looloo.woom;
  component [foo-baz-protoype-sisi] as foo.sisi.woom;
  component "foo-baz-frame" as foo.frame.woom;
};
component "moo"{;
  package [foo-baz-frame] <<artifact:npm>> as foo.frame.npm;
  package [foo-buzz] <<artifact:npm>> as foo.buzz.npm;
  package [foo-looloo] as foo.looloo.npm;
  package [foo-baz-protoype-sisi] as foo.sisi.npm;
};
component "spee"{;
  component [foo-bar] <<staging>> as foo.pp.ham.app;
  component [foo-baz-fizz] <<staging>> as foo.bs.ham.app;
  component [foo-bar] <<production>> as foo.pp.cloud.app;
  component [foo-baz-fizz] <<production>> as foo.bs.cloud.app;
};
component "shrimps"{;
  node [schoo/foo-bar] <<artifact:fooofoo>> as foo.pp.ramp;
  node [schoo/foo-baz-fizz] <<artifact:fooofoo>> as foo.bs.ramp;
};
foo.pp.git ..> foo.pp.ham.woom;
foo.pp.git ..> foo.buzz.woom;
foo.bs.git ..> foo.bs.woom;
foo.looloo.git ..> foo.looloo.woom;
foo.sisi.git ..> foo.sisi.woom;
foo.frame.git => foo.frame.woom;
foo.looloo.woom => foo.looloo.npm;
foo.buzz.woom => foo.buzz.npm;
foo.sisi.woom => foo.sisi.npm;
foo.frame.woom => foo.frame.npm;
foo.looloo.npm ..> foo.pp.ham.woom;
foo.buzz.npm ..> foo.bs.woom;
foo.buzz.npm ..> foo.sums;
foo.frame.npm ..> foo.bs.woom;
foo.frame.npm ..> foo.sums;
foo.sisi.npm ..> foo.bs.woom;
foo.pp.ham.woom => foo.pp.ramp;
foo.bs.woom => foo.bs.ramp;
foo.pp.ham.app <.. foo.pp.ramp;
foo.bs.ham.app <.. foo.bs.ramp;
foo.pp.cloud.app <.. foo.pp.ramp;
foo.bs.cloud.app <.. foo.bs.ramp;
foo.pp.ham.woom ..> foo.pp.ham.deploy;
foo.pp.ham.woom ..> foo.pp.cloud.deploy;
foo.bs.woom ..> foo.bs.ham.deploy;
foo.bs.woom ..> foo.bs.cloud.deploy;
foo.pp.ham.deploy ==> foo.pp.ham.app;
foo.pp.cloud.deploy ==> foo.pp.cloud.app;
foo.bs.ham.deploy ==> foo.bs.ham.app;
foo.bs.cloud.deploy ==> foo.bs.cloud.app;
@enduml
)
```

**Comment by TLmaK0** [comment]
Thanks @marionebl I will take a look.

**Comment by TLmaK0** [comment]
I can render it correctly pasting your code directly:

![woo](http://g.gravizo.com/g?
@startuml;
skinparam monochrome true;
skinparam shadowing false;
skinparam component {;
  backgroundColor<<artifact:npm>> lightgray;
  componentFontColor<<artifact:fooofoo>> white;
};
component "meh" {;
  component [foo-bar] as foo.pp.git;
  component [foo-baz-fizz] as foo.bs.git;
  component [foo-looloo] as foo.looloo.git;
  component [foo-baz-protoype-sisi] as foo.sisi.git;
  component [foo-baz-frame] as foo.frame.git;
};
component "mah" {;
  component [foo-bar-ham] as foo.pp.ham.woom;
  component [foo-bar-ham-deploy] as foo.pp.ham.deploy;
  component [foo-bar-cloud-deploy] as foo.pp.cloud.deploy;
  component [foo-buzz] as foo.buzz.woom;
  component [foo-baz-fizz-ham-deploy] as foo.bs.ham.deploy;
  component [foo-baz-fizz-cloud-deploy] as foo.bs.cloud.deploy;
  component [foo-baz-fizz-ham] as foo.bs.woom;
  component "foo-baz-sums" as foo.sums;
  component [foo-looloo] as foo.looloo.woom;
  component [foo-baz-protoype-sisi] as foo.sisi.woom;
  component "foo-baz-frame" as foo.frame.woom;
};
component "moo"{;
  package [foo-baz-frame] <<artifact:npm>> as foo.frame.npm;
  package [foo-buzz] <<artifact:npm>> as foo.buzz.npm;
  package [foo-looloo] as foo.looloo.npm;
  package [foo-baz-protoype-sisi] as foo.sisi.npm;
};
component "spee"{;
  component [foo-bar] <<staging>> as foo.pp.ham.app;
  component [foo-baz-fizz] <<staging>> as foo.bs.ham.app;
  component [foo-bar] <<production>> as foo.pp.cloud.app;
  component [foo-baz-fizz] <<production>> as foo.bs.cloud.app;
};
component "shrimps"{;
  node [schoo/foo-bar] <<artifact:fooofoo>> as foo.pp.ramp;
  node [schoo/foo-baz-fizz] <<artifact:fooofoo>> as foo.bs.ramp;
};
foo.pp.git ..> foo.pp.ham.woom;
foo.pp.git ..> foo.buzz.woom;
foo.bs.git ..> foo.bs.woom;
foo.looloo.git ..> foo.looloo.woom;
foo.sisi.git ..> foo.sisi.woom;
foo.frame.git => foo.frame.woom;
foo.looloo.woom => foo.looloo.npm;
foo.buzz.woom => foo.buzz.npm;
foo.sisi.woom => foo.sisi.npm;
foo.frame.woom => foo.frame.npm;
foo.looloo.npm ..> foo.pp.ham.woom;
foo.buzz.npm ..> foo.bs.woom;
foo.buzz.npm ..> foo.sums;
foo.frame.npm ..> foo.bs.woom;
foo.frame.npm ..> foo.sums;
foo.sisi.npm ..> foo.bs.woom;
foo.pp.ham.woom => foo.pp.ramp;
foo.bs.woom => foo.bs.ramp;
foo.pp.ham.app <.. foo.pp.ramp;
foo.bs.ham.app <.. foo.bs.ramp;
foo.pp.cloud.app <.. foo.pp.ramp;
foo.bs.cloud.app <.. foo.bs.ramp;
foo.pp.ham.woom ..> foo.pp.ham.deploy;
foo.pp.ham.woom ..> foo.pp.cloud.deploy;
foo.bs.woom ..> foo.bs.ham.deploy;
foo.bs.woom ..> foo.bs.cloud.deploy;
foo.pp.ham.deploy ==> foo.pp.ham.app;
foo.pp.cloud.deploy ==> foo.pp.cloud.app;
foo.bs.ham.deploy ==> foo.bs.ham.app;
foo.bs.cloud.deploy ==> foo.bs.cloud.app;
@enduml
)

Can you test again? Could it be a race condition?

**Comment by marionebl** [comment]
Seems to work now, thanks!

2016-02-06 16:01 GMT+01:00 Hugo Freire Gil <notifications@github.com>:

**Comment by TLmaK0** [comment]
I need to investigate it. Yesterday It fails again.
![screenshot](https://cloud.githubusercontent.com/assets/399935/13371940/be247df8-dd32-11e5-80c5-2156661579be.png)

**Comment by TLmaK0** [comment]
Fixed
